apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-trading-bot
  namespace: trading
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold-trading-bot
  template:
    metadata:
      labels:
        app: gold-trading-bot
    spec:
      containers:
      - name: trading-bot
        image: trading-registry.azurecr.io/gold-trading-bot:latest
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
        env:
        - name: MT5_SERVER
          valueFrom:
            secretKeyRef:
              name: mt5-credentials
              key: server
        - name: MT5_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: mt5-credentials
              key: account
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: models-volume
          mountPath: /app/models
      volumes:
      - name: config-volume
        configMap:
          name: trading-bot-config
      - name: models-volume
        persistentVolumeClaim:
          claimName: ml-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
spec:
  selector:
    app: gold-trading-bot
  ports:
  - port: 8080
    targetPort: 8080
